name: flutter_sqlite_local_storage
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  enum_to_string: ^2.0.1
  intl: ^0.17.0
  path_provider: ^2.0.1
  sqflite: ^2.0.0+3

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
